<?php

namespace Database\Seeders;

use App\Domains\Institucional\Models\Carrera;
use App\Domains\Institucional\Models\Colegio;
use App\Domains\Postulantes\Models\Postulante;
use Illuminate\Database\Seeder;

class PostulantesSeeder extends Seeder
{
    public function run(): void
    {
        // Standalone academic fixtures intentionally have no digital account.
        // Never infer user_id from contact data or overwrite an existing explicit link.
        $colegios = Colegio::pluck('id_col', 'nombre_col');
        $carreras = Carrera::query()
            ->with('universidad:id_uni,sigla_uni')
            ->get()
            ->keyBy(fn (Carrera $carrera) => "{$carrera->universidad->sigla_uni}|{$carrera->nombre_car}");

        $postulantes = [
            // ── UMSA (24 postulantes ≈ 40 %) ──────────────────────────────
            ['nombres_post' => 'María Fernanda',  'apellidos_post' => 'López Vargas',     'ci_post' => '8945121', 'email_post' => 'maria.lopez@correo.test',       'celular_post' => '72014521', 'fecha_nacimiento_post' => '2005-08-15', 'colegio' => 'Colegio Nacional Ayacucho',              'universidad' => 'UMSA', 'carrera' => 'Ingeniería de Sistemas',   'turno_post' => 'Mañana', 'gestion_post' => 2026, 'estado_post' => 'activo'],
            ['nombres_post' => 'José Luis',        'apellidos_post' => 'Mamani Quispe',    'ci_post' => '6812457', 'email_post' => 'jose.mamani@correo.test',        'celular_post' => '67541209', 'fecha_nacimiento_post' => '2007-03-22', 'colegio' => 'Colegio Bolívar',                       'universidad' => 'UMSA', 'carrera' => 'Ingeniería Civil',          'turno_post' => 'Noche',  'gestion_post' => 2026, 'estado_post' => 'activo'],
            ['nombres_post' => 'Miguel Ángel',     'apellidos_post' => 'Sánchez Lima',     'ci_post' => '7926415', 'email_post' => 'miguel.sanchez@correo.test',     'celular_post' => '75261489', 'fecha_nacimiento_post' => '2008-02-29', 'colegio' => 'Colegio Don Bosco',                     'universidad' => 'UMSA', 'carrera' => 'Ingeniería de Sistemas',   'turno_post' => 'Tarde',  'gestion_post' => 2026, 'estado_post' => 'activo'],
            ['nombres_post' => 'Ana Patricia',     'apellidos_post' => 'Condori Apaza',    'ci_post' => '9015342', 'email_post' => 'ana.condori@correo.test',        'celular_post' => '71239845', 'fecha_nacimiento_post' => '2004-11-09', 'colegio' => 'Colegio San Calixto',                   'universidad' => 'UMSA', 'carrera' => 'Ingeniería Civil',          'turno_post' => 'Mañana', 'gestion_post' => 2026, 'estado_post' => 'activo'],
            ['nombres_post' => 'Rodrigo',          'apellidos_post' => 'Choque Huanca',    'ci_post' => '7348920', 'email_post' => 'rodrigo.choque@correo.test',     'celular_post' => '76483021', 'fecha_nacimiento_post' => '2009-06-18', 'colegio' => 'Colegio La Salle',                      'universidad' => 'UMSA', 'carrera' => 'Ingeniería Industrial',     'turno_post' => 'Mañana', 'gestion_post' => 2026, 'estado_post' => 'activo'],
            ['nombres_post' => 'Fabiola',          'apellidos_post' => 'Quispe Tito',      'ci_post' => '8237614', 'email_post' => 'fabiola.quispe@correo.test',     'celular_post' => '70394821', 'fecha_nacimiento_post' => '2006-12-03', 'colegio' => 'Unidad Educativa Integración Andina',   'universidad' => 'UMSA', 'carrera' => 'Ingeniería Industrial',     'turno_post' => 'Tarde',  'gestion_post' => 2026, 'estado_post' => 'activo'],
            ['nombres_post' => 'Ernesto',          'apellidos_post' => 'Torrico Medina',   'ci_post' => '6591038', 'email_post' => 'ernesto.torrico@correo.test',    'celular_post' => '68123904', 'fecha_nacimiento_post' => '2003-04-27', 'colegio' => 'Colegio Nacional Ayacucho',              'universidad' => 'UMSA', 'carrera' => 'Economía',                  'turno_post' => 'Noche',  'gestion_post' => 2026, 'estado_post' => 'activo'],
            ['nombres_post' => 'Luciana',          'apellidos_post' => 'Bernal Soliz',     'ci_post' => '9462031', 'email_post' => 'luciana.bernal@correo.test',     'celular_post' => '72498310', 'fecha_nacimiento_post' => '2002-09-14', 'colegio' => 'Colegio Bolívar',                       'universidad' => 'UMSA', 'carrera' => 'Economía',                  'turno_post' => 'Mañana', 'gestion_post' => 2026, 'estado_post' => 'activo'],
            ['nombres_post' => 'Fernando',         'apellidos_post' => 'Aliaga Ramos',     'ci_post' => '7801293', 'email_post' => 'fernando.aliaga@correo.test',    'celular_post' => '75120493', 'fecha_nacimiento_post' => '2008-07-06', 'colegio' => 'Colegio La Salle',                      'universidad' => 'UMSA', 'carrera' => 'Administración de Empresas', 'turno_post' => 'Tarde',  'gestion_post' => 2026, 'estado_post' => 'activo'],
            ['nombres_post' => 'Paola',            'apellidos_post' => 'Vargas Limachi',   'ci_post' => '8390147', 'email_post' => 'paola.vargas@correo.test',       'celular_post' => '76309142', 'fecha_nacimiento_post' => '2001-05-21', 'colegio' => 'Colegio San Calixto',                   'universidad' => 'UMSA', 'carrera' => 'Administración de Empresas', 'turno_post' => 'Mañana', 'gestion_post' => 2026, 'estado_post' => 'activo'],
            ['nombres_post' => 'Luis Fernando',    'apellidos_post' => 'Vega Torrico',     'ci_post' => '7145289', 'email_post' => 'luis.vega@correo.test',          'celular_post' => '69451728', 'fecha_nacimiento_post' => '2007-10-12', 'colegio' => 'Colegio Don Bosco',                     'universidad' => 'UMSA', 'carrera' => 'Derecho',                   'turno_post' => 'Noche',  'gestion_post' => 2026, 'estado_post' => 'inactivo'],
            ['nombres_post' => 'Valentina',        'apellidos_post' => 'Cruz Salazar',     'ci_post' => '9256134', 'email_post' => 'valentina.cruz@correo.test',     'celular_post' => '70783120', 'fecha_nacimiento_post' => '2009-01-24', 'colegio' => 'Unidad Educativa Integración Andina',   'universidad' => 'UMSA', 'carrera' => 'Psicología',                'turno_post' => 'Mañana', 'gestion_post' => 2026, 'estado_post' => 'activo'],
            ['nombres_post' => 'Gabriel',          'apellidos_post' => 'Paredes Alanoca',  'ci_post' => '8104876', 'email_post' => 'gabriel.paredes@correo.test',    'celular_post' => '73291048', 'fecha_nacimiento_post' => '2005-08-15', 'colegio' => 'Colegio Nacional Ayacucho',              'universidad' => 'UMSA', 'carrera' => 'Psicología',                'turno_post' => 'Tarde',  'gestion_post' => 2026, 'estado_post' => 'activo'],
            ['nombres_post' => 'Daniela',          'apellidos_post' => 'Flores Reyes',     'ci_post' => '9673425', 'email_post' => 'daniela.flores@correo.test',     'celular_post' => '71845293', 'fecha_nacimiento_post' => '2007-03-22', 'colegio' => 'Colegio Técnico Humanístico El Alto',   'universidad' => 'UMSA', 'carrera' => 'Ingeniería Industrial',     'turno_post' => 'Mañana', 'gestion_post' => 2026, 'estado_post' => 'activo'],
            ['nombres_post' => 'Sebastián',        'apellidos_post' => 'Nina Espinoza',    'ci_post' => '7492016', 'email_post' => 'sebastian.nina@correo.test',     'celular_post' => '76021394', 'fecha_nacimiento_post' => '2008-02-29', 'colegio' => 'Unidad Educativa República de Venezuela', 'universidad' => 'UMSA', 'carrera' => 'Ingeniería de Sistemas',   'turno_post' => 'Tarde',  'gestion_post' => 2026, 'estado_post' => 'activo'],
            ['nombres_post' => 'Vanessa',          'apellidos_post' => 'Chacón Pérez',     'ci_post' => '8815034', 'email_post' => 'vanessa.chacon@correo.test',     'celular_post' => '72934810', 'fecha_nacimiento_post' => '2004-11-09', 'colegio' => 'Colegio Bolívar',                       'universidad' => 'UMSA', 'carrera' => 'Ingeniería Civil',          'turno_post' => 'Mañana', 'gestion_post' => 2026, 'estado_post' => 'activo'],
            ['nombres_post' => 'Marcelo',          'apellidos_post' => 'Loza Gutierrez',   'ci_post' => '6923418', 'email_post' => 'marcelo.loza@correo.test',       'celular_post' => '67948230', 'fecha_nacimiento_post' => '2009-06-18', 'colegio' => 'Colegio La Salle',                      'universidad' => 'UMSA', 'carrera' => 'Economía',                  'turno_post' => 'Noche',  'gestion_post' => 2026, 'estado_post' => 'activo'],
            ['nombres_post' => 'Cecilia',          'apellidos_post' => 'Yujra Callisaya',  'ci_post' => '9341062', 'email_post' => 'cecilia.yujra@correo.test',      'celular_post' => '70481263', 'fecha_nacimiento_post' => '2006-12-03', 'colegio' => 'Colegio Técnico Humanístico El Alto',   'universidad' => 'UMSA', 'carrera' => 'Administración de Empresas', 'turno_post' => 'Tarde',  'gestion_post' => 2026, 'estado_post' => 'activo'],
            ['nombres_post' => 'Roberto',          'apellidos_post' => 'Poma Ticona',      'ci_post' => '7580231', 'email_post' => 'roberto.poma@correo.test',       'celular_post' => '75843012', 'fecha_nacimiento_post' => '2003-04-27', 'colegio' => 'Unidad Educativa República de Venezuela', 'universidad' => 'UMSA', 'carrera' => 'Ingeniería Civil',          'turno_post' => 'Mañana', 'gestion_post' => 2026, 'estado_post' => 'activo'],
            ['nombres_post' => 'Ximena',           'apellidos_post' => 'Arce Villanueva',  'ci_post' => '9028346', 'email_post' => 'ximena.arce@correo.test',        'celular_post' => '71392048', 'fecha_nacimiento_post' => '2002-09-14', 'colegio' => 'Unidad Educativa Integración Andina',   'universidad' => 'UMSA', 'carrera' => 'Derecho',                   'turno_post' => 'Tarde',  'gestion_post' => 2026, 'estado_post' => 'inactivo'],
            ['nombres_post' => 'Álvaro',           'apellidos_post' => 'Mendoza Carrasco', 'ci_post' => '7263945', 'email_post' => 'alvaro.mendoza@correo.test',     'celular_post' => '76394821', 'fecha_nacimiento_post' => '2008-07-06', 'colegio' => 'Colegio San Calixto',                   'universidad' => 'UMSA', 'carrera' => 'Ingeniería Industrial',     'turno_post' => 'Mañana', 'gestion_post' => 2026, 'estado_post' => 'activo'],
            ['nombres_post' => 'Patricia',         'apellidos_post' => 'Rocha Beltrán',    'ci_post' => '8716024', 'email_post' => 'patricia.rocha@correo.test',     'celular_post' => '72019348', 'fecha_nacimiento_post' => '2001-05-21', 'colegio' => 'Colegio Don Bosco',                     'universidad' => 'UMSA', 'carrera' => 'Psicología',                'turno_post' => 'Tarde',  'gestion_post' => 2026, 'estado_post' => 'activo'],
            ['nombres_post' => 'Iván',             'apellidos_post' => 'Colque Achá',      'ci_post' => '6490823', 'email_post' => 'ivan.colque@correo.test',        'celular_post' => '68023491', 'fecha_nacimiento_post' => '2007-10-12', 'colegio' => 'Colegio Nacional Ayacucho',              'universidad' => 'UMSA', 'carrera' => 'Economía',                  'turno_post' => 'Noche',  'gestion_post' => 2026, 'estado_post' => 'activo'],
            ['nombres_post' => 'Norma',            'apellidos_post' => 'Surco Mamani',     'ci_post' => '9182047', 'email_post' => 'norma.surco@correo.test',        'celular_post' => '71829043', 'fecha_nacimiento_post' => '2009-01-24', 'colegio' => 'Colegio Bolívar',                       'universidad' => 'UMSA', 'carrera' => 'Administración de Empresas', 'turno_post' => 'Mañana', 'gestion_post' => 2026, 'estado_post' => 'activo'],

            // ── EMI (12 postulantes ≈ 20 %) ───────────────────────────────
            ['nombres_post' => 'Carlos Andrés',    'apellidos_post' => 'Rojas Méndez',     'ci_post' => '7632198', 'email_post' => 'carlos.rojas@correo.test',       'celular_post' => '76403218', 'fecha_nacimiento_post' => '2005-08-15', 'colegio' => 'Colegio La Salle',                      'universidad' => 'EMI',  'carrera' => 'Ingeniería Comercial',      'turno_post' => 'Tarde',  'gestion_post' => 2026, 'estado_post' => 'activo'],
            ['nombres_post' => 'Diego Alejandro',  'apellidos_post' => 'Paredes Soto',     'ci_post' => '8451726', 'email_post' => 'diego.paredes@correo.test',      'celular_post' => '75963124', 'fecha_nacimiento_post' => '2007-03-22', 'colegio' => 'Colegio San Calixto',                   'universidad' => 'EMI',  'carrera' => 'Ingeniería de Sistemas',   'turno_post' => 'Mañana', 'gestion_post' => 2026, 'estado_post' => 'activo'],
            ['nombres_post' => 'Alejandro',        'apellidos_post' => 'Espinoza Cárdenas', 'ci_post' => '8620349', 'email_post' => 'alejandro.espinoza@correo.test', 'celular_post' => '76230419', 'fecha_nacimiento_post' => '2008-02-29', 'colegio' => 'Unidad Educativa Integración Andina',   'universidad' => 'EMI',  'carrera' => 'Ingeniería Mecatrónica',    'turno_post' => 'Mañana', 'gestion_post' => 2026, 'estado_post' => 'activo'],
            ['nombres_post' => 'Claudia',          'apellidos_post' => 'Baldivia Roca',    'ci_post' => '9534082', 'email_post' => 'claudia.baldivia@correo.test',   'celular_post' => '71583024', 'fecha_nacimiento_post' => '2004-11-09', 'colegio' => 'Colegio Nacional Ayacucho',              'universidad' => 'EMI',  'carrera' => 'Ingeniería Civil',          'turno_post' => 'Tarde',  'gestion_post' => 2026, 'estado_post' => 'activo'],
            ['nombres_post' => 'Emilio',           'apellidos_post' => 'Sejas Ramírez',    'ci_post' => '7093415', 'email_post' => 'emilio.sejas@correo.test',       'celular_post' => '69041385', 'fecha_nacimiento_post' => '2009-06-18', 'colegio' => 'Colegio Don Bosco',                     'universidad' => 'EMI',  'carrera' => 'Ingeniería de Sistemas',   'turno_post' => 'Noche',  'gestion_post' => 2026, 'estado_post' => 'activo'],
            ['nombres_post' => 'Sandra',           'apellidos_post' => 'Guzmán Torres',    'ci_post' => '8819206', 'email_post' => 'sandra.guzman@correo.test',      'celular_post' => '72891046', 'fecha_nacimiento_post' => '2006-12-03', 'colegio' => 'Colegio Bolívar',                       'universidad' => 'EMI',  'carrera' => 'Ingeniería Comercial',      'turno_post' => 'Mañana', 'gestion_post' => 2026, 'estado_post' => 'activo'],
            ['nombres_post' => 'Hugo',             'apellidos_post' => 'Limachi Cori',     'ci_post' => '7341890', 'email_post' => 'hugo.limachi@correo.test',       'celular_post' => '75348210', 'fecha_nacimiento_post' => '2003-04-27', 'colegio' => 'Colegio Técnico Humanístico El Alto',   'universidad' => 'EMI',  'carrera' => 'Ingeniería Mecatrónica',    'turno_post' => 'Tarde',  'gestion_post' => 2026, 'estado_post' => 'activo'],
            ['nombres_post' => 'Adriana',          'apellidos_post' => 'Calle Mercado',    'ci_post' => '9105738', 'email_post' => 'adriana.calle@correo.test',      'celular_post' => '71059382', 'fecha_nacimiento_post' => '2002-09-14', 'colegio' => 'Unidad Educativa República de Venezuela', 'universidad' => 'EMI',  'carrera' => 'Ingeniería Civil',          'turno_post' => 'Mañana', 'gestion_post' => 2026, 'estado_post' => 'activo'],
            ['nombres_post' => 'Bernardo',         'apellidos_post' => 'Zenteno Aranda',   'ci_post' => '8283401', 'email_post' => 'bernardo.zenteno@correo.test',   'celular_post' => '76284301', 'fecha_nacimiento_post' => '2008-07-06', 'colegio' => 'Colegio La Salle',                      'universidad' => 'EMI',  'carrera' => 'Ingeniería de Sistemas',   'turno_post' => 'Tarde',  'gestion_post' => 2026, 'estado_post' => 'activo'],
            ['nombres_post' => 'Verónica',         'apellidos_post' => 'Marca Huayta',     'ci_post' => '9638124', 'email_post' => 'veronica.marca@correo.test',     'celular_post' => '70638124', 'fecha_nacimiento_post' => '2001-05-21', 'colegio' => 'Colegio San Calixto',                   'universidad' => 'EMI',  'carrera' => 'Ingeniería Comercial',      'turno_post' => 'Mañana', 'gestion_post' => 2026, 'estado_post' => 'activo'],
            ['nombres_post' => 'Oscar',            'apellidos_post' => 'Soria Aguilar',    'ci_post' => '7520841', 'email_post' => 'oscar.soria@correo.test',        'celular_post' => '75208410', 'fecha_nacimiento_post' => '2007-10-12', 'colegio' => 'Unidad Educativa Integración Andina',   'universidad' => 'EMI',  'carrera' => 'Ingeniería Civil',          'turno_post' => 'Noche',  'gestion_post' => 2026, 'estado_post' => 'activo'],
            ['nombres_post' => 'Rosa Elena',       'apellidos_post' => 'Ticona Blanco',    'ci_post' => '8960237', 'email_post' => 'rosa.ticona@correo.test',        'celular_post' => '71960237', 'fecha_nacimiento_post' => '2009-01-24', 'colegio' => 'Colegio Nacional Ayacucho',              'universidad' => 'EMI',  'carrera' => 'Ingeniería Mecatrónica',    'turno_post' => 'Tarde',  'gestion_post' => 2026, 'estado_post' => 'activo'],

            // ── UCB (9 postulantes ≈ 15 %) ────────────────────────────────
            ['nombres_post' => 'Camila',           'apellidos_post' => 'Gutiérrez Arce',   'ci_post' => '9362184', 'email_post' => 'camila.gutierrez@correo.test',   'celular_post' => '70321846', 'fecha_nacimiento_post' => '2005-08-15', 'colegio' => 'Colegio La Salle',                      'universidad' => 'UCB',  'carrera' => 'Economía',                  'turno_post' => 'Tarde',  'gestion_post' => 2026, 'estado_post' => 'activo'],
            ['nombres_post' => 'Jimena',           'apellidos_post' => 'Montaño Cabrera',  'ci_post' => '8590273', 'email_post' => 'jimena.montano@correo.test',     'celular_post' => '72059273', 'fecha_nacimiento_post' => '2007-03-22', 'colegio' => 'Colegio San Calixto',                   'universidad' => 'UCB',  'carrera' => 'Administración de Empresas', 'turno_post' => 'Mañana', 'gestion_post' => 2026, 'estado_post' => 'activo'],
            ['nombres_post' => 'Tomás',            'apellidos_post' => 'Velarde Fuentes',  'ci_post' => '7204893', 'email_post' => 'tomas.velarde@correo.test',      'celular_post' => '76204893', 'fecha_nacimiento_post' => '2008-02-29', 'colegio' => 'Colegio Don Bosco',                     'universidad' => 'UCB',  'carrera' => 'Ingeniería Comercial',      'turno_post' => 'Tarde',  'gestion_post' => 2026, 'estado_post' => 'activo'],
            ['nombres_post' => 'Gabriela',         'apellidos_post' => 'Cárdenas Villca',  'ci_post' => '9481023', 'email_post' => 'gabriela.cardenas@correo.test',  'celular_post' => '71481023', 'fecha_nacimiento_post' => '2004-11-09', 'colegio' => 'Unidad Educativa Integración Andina',   'universidad' => 'UCB',  'carrera' => 'Psicología',                'turno_post' => 'Mañana', 'gestion_post' => 2026, 'estado_post' => 'activo'],
            ['nombres_post' => 'Cristian',         'apellidos_post' => 'Apaza Chura',      'ci_post' => '8027394', 'email_post' => 'cristian.apaza@correo.test',     'celular_post' => '75027394', 'fecha_nacimiento_post' => '2009-06-18', 'colegio' => 'Colegio Nacional Ayacucho',              'universidad' => 'UCB',  'carrera' => 'Economía',                  'turno_post' => 'Noche',  'gestion_post' => 2026, 'estado_post' => 'activo'],
            ['nombres_post' => 'Miriam',           'apellidos_post' => 'Aguilar Tapia',    'ci_post' => '9650182', 'email_post' => 'miriam.aguilar@correo.test',     'celular_post' => '70650182', 'fecha_nacimiento_post' => '2006-12-03', 'colegio' => 'Colegio Bolívar',                       'universidad' => 'UCB',  'carrera' => 'Psicología',                'turno_post' => 'Tarde',  'gestion_post' => 2026, 'estado_post' => 'activo'],
            ['nombres_post' => 'Rafael',           'apellidos_post' => 'Aramayo Loza',     'ci_post' => '7810426', 'email_post' => 'rafael.aramayo@correo.test',     'celular_post' => '76810426', 'fecha_nacimiento_post' => '2003-04-27', 'colegio' => 'Colegio Técnico Humanístico El Alto',   'universidad' => 'UCB',  'carrera' => 'Administración de Empresas', 'turno_post' => 'Mañana', 'gestion_post' => 2026, 'estado_post' => 'activo'],
            ['nombres_post' => 'Silvia',           'apellidos_post' => 'Porcel Montes',    'ci_post' => '9074512', 'email_post' => 'silvia.porcel@correo.test',      'celular_post' => '71074512', 'fecha_nacimiento_post' => '2002-09-14', 'colegio' => 'Unidad Educativa República de Venezuela', 'universidad' => 'UCB',  'carrera' => 'Ingeniería Comercial',      'turno_post' => 'Tarde',  'gestion_post' => 2026, 'estado_post' => 'activo'],
            ['nombres_post' => 'Nicolás',          'apellidos_post' => 'Callisaya Ramos',  'ci_post' => '8432091', 'email_post' => 'nicolas.callisaya@correo.test',  'celular_post' => '75432091', 'fecha_nacimiento_post' => '2008-07-06', 'colegio' => 'Colegio La Salle',                      'universidad' => 'UCB',  'carrera' => 'Economía',                  'turno_post' => 'Mañana', 'gestion_post' => 2026, 'estado_post' => 'activo'],

            // ── UNIFRANZ (9 postulantes ≈ 15 %) ──────────────────────────
            ['nombres_post' => 'Andrea Sofía',     'apellidos_post' => 'Flores Rocha',     'ci_post' => '9124875', 'email_post' => 'andrea.flores@correo.test',      'celular_post' => '72241865', 'fecha_nacimiento_post' => '2001-05-21', 'colegio' => 'Colegio San Calixto',                   'universidad' => 'UNIFRANZ', 'carrera' => 'Ingeniería de Sistemas',    'turno_post' => 'Tarde',  'gestion_post' => 2026, 'estado_post' => 'activo'],
            ['nombres_post' => 'Liseth',           'apellidos_post' => 'Morales Ordóñez',  'ci_post' => '8261049', 'email_post' => 'liseth.morales@correo.test',     'celular_post' => '72610489', 'fecha_nacimiento_post' => '2007-10-12', 'colegio' => 'Unidad Educativa Integración Andina',   'universidad' => 'UNIFRANZ', 'carrera' => 'Administración de Empresas', 'turno_post' => 'Mañana', 'gestion_post' => 2026, 'estado_post' => 'activo'],
            ['nombres_post' => 'Eduardo',          'apellidos_post' => 'Cuentas Quisbert', 'ci_post' => '7483021', 'email_post' => 'eduardo.cuentas@correo.test',    'celular_post' => '76483021', 'fecha_nacimiento_post' => '2009-01-24', 'colegio' => 'Colegio Nacional Ayacucho',              'universidad' => 'UNIFRANZ', 'carrera' => 'Medicina',                  'turno_post' => 'Mañana', 'gestion_post' => 2026, 'estado_post' => 'activo'],
            ['nombres_post' => 'Mariela',          'apellidos_post' => 'Pinto Cabrera',    'ci_post' => '9318047', 'email_post' => 'mariela.pinto@correo.test',      'celular_post' => '70318047', 'fecha_nacimiento_post' => '2005-08-15', 'colegio' => 'Colegio Bolívar',                       'universidad' => 'UNIFRANZ', 'carrera' => 'Ingeniería de Sistemas',    'turno_post' => 'Tarde',  'gestion_post' => 2026, 'estado_post' => 'activo'],
            ['nombres_post' => 'Dante',            'apellidos_post' => 'Quispe Layme',     'ci_post' => '7620384', 'email_post' => 'dante.quispe@correo.test',       'celular_post' => '75620384', 'fecha_nacimiento_post' => '2007-03-22', 'colegio' => 'Colegio Don Bosco',                     'universidad' => 'UNIFRANZ', 'carrera' => 'Administración de Empresas', 'turno_post' => 'Noche',  'gestion_post' => 2026, 'estado_post' => 'activo'],
            ['nombres_post' => 'Karla',            'apellidos_post' => 'Heredia Fuentes',  'ci_post' => '8905231', 'email_post' => 'karla.heredia@correo.test',      'celular_post' => '71905231', 'fecha_nacimiento_post' => '2008-02-29', 'colegio' => 'Colegio La Salle',                      'universidad' => 'UNIFRANZ', 'carrera' => 'Medicina',                  'turno_post' => 'Mañana', 'gestion_post' => 2026, 'estado_post' => 'activo'],
            ['nombres_post' => 'Renato',           'apellidos_post' => 'Burgoa Escalera',  'ci_post' => '7058293', 'email_post' => 'renato.burgoa@correo.test',      'celular_post' => '75058293', 'fecha_nacimiento_post' => '2004-11-09', 'colegio' => 'Colegio Técnico Humanístico El Alto',   'universidad' => 'UNIFRANZ', 'carrera' => 'Ingeniería de Sistemas',    'turno_post' => 'Tarde',  'gestion_post' => 2026, 'estado_post' => 'activo'],
            ['nombres_post' => 'Alejandra',        'apellidos_post' => 'Mamani Tito',      'ci_post' => '9426018', 'email_post' => 'alejandra.mamani@correo.test',   'celular_post' => '70426018', 'fecha_nacimiento_post' => '2009-06-18', 'colegio' => 'Unidad Educativa República de Venezuela', 'universidad' => 'UNIFRANZ', 'carrera' => 'Administración de Empresas', 'turno_post' => 'Mañana', 'gestion_post' => 2026, 'estado_post' => 'activo'],
            ['nombres_post' => 'Mauricio',         'apellidos_post' => 'Solares Chávez',   'ci_post' => '8172043', 'email_post' => 'mauricio.solares@correo.test',   'celular_post' => '76172043', 'fecha_nacimiento_post' => '2006-12-03', 'colegio' => 'Colegio San Calixto',                   'universidad' => 'UNIFRANZ', 'carrera' => 'Medicina',                  'turno_post' => 'Tarde',  'gestion_post' => 2026, 'estado_post' => 'activo'],

            // ── UPEA (6 postulantes ≈ 10 %) ───────────────────────────────
            ['nombres_post' => 'Natalia Belén',    'apellidos_post' => 'Rivera Campos',    'ci_post' => '9581243', 'email_post' => 'natalia.rivera@correo.test',     'celular_post' => '71894523', 'fecha_nacimiento_post' => '2003-04-27', 'colegio' => 'Colegio Técnico Humanístico El Alto',   'universidad' => 'UPEA', 'carrera' => 'Ciencias de la Educación',  'turno_post' => 'Mañana', 'gestion_post' => 2026, 'estado_post' => 'activo'],
            ['nombres_post' => 'Edwin',            'apellidos_post' => 'Huanca Pari',      'ci_post' => '7390264', 'email_post' => 'edwin.huanca@correo.test',       'celular_post' => '75390264', 'fecha_nacimiento_post' => '2002-09-14', 'colegio' => 'Unidad Educativa República de Venezuela', 'universidad' => 'UPEA', 'carrera' => 'Ingeniería de Sistemas',   'turno_post' => 'Noche',  'gestion_post' => 2026, 'estado_post' => 'activo'],
            ['nombres_post' => 'Elvira',           'apellidos_post' => 'Coaquira Mamani',  'ci_post' => '8640179', 'email_post' => 'elvira.coaquira@correo.test',    'celular_post' => '72640179', 'fecha_nacimiento_post' => '2008-07-06', 'colegio' => 'Colegio Técnico Humanístico El Alto',   'universidad' => 'UPEA', 'carrera' => 'Contaduría Pública',        'turno_post' => 'Tarde',  'gestion_post' => 2026, 'estado_post' => 'activo'],
            ['nombres_post' => 'Samuel',           'apellidos_post' => 'Llanos Vargas',    'ci_post' => '9207431', 'email_post' => 'samuel.llanos@correo.test',      'celular_post' => '70207431', 'fecha_nacimiento_post' => '2001-05-21', 'colegio' => 'Unidad Educativa República de Venezuela', 'universidad' => 'UPEA', 'carrera' => 'Ciencias de la Educación',  'turno_post' => 'Mañana', 'gestion_post' => 2026, 'estado_post' => 'activo'],
            ['nombres_post' => 'Cinthia',          'apellidos_post' => 'Condori Roque',    'ci_post' => '8058413', 'email_post' => 'cinthia.condori@correo.test',    'celular_post' => '75058413', 'fecha_nacimiento_post' => '2007-10-12', 'colegio' => 'Colegio Nacional Ayacucho',              'universidad' => 'UPEA', 'carrera' => 'Contaduría Pública',        'turno_post' => 'Tarde',  'gestion_post' => 2026, 'estado_post' => 'activo'],
            ['nombres_post' => 'Alberto',          'apellidos_post' => 'Cutipa Flores',    'ci_post' => '7731048', 'email_post' => 'alberto.cutipa@correo.test',     'celular_post' => '76731048', 'fecha_nacimiento_post' => '2009-01-24', 'colegio' => 'Colegio Bolívar',                       'universidad' => 'UPEA', 'carrera' => 'Ingeniería de Sistemas',   'turno_post' => 'Noche',  'gestion_post' => 2026, 'estado_post' => 'activo'],
        ];

        foreach ($postulantes as $postulante) {
            $colegio = $postulante['colegio'];
            $carreraKey = "{$postulante['universidad']}|{$postulante['carrera']}";
            unset($postulante['colegio'], $postulante['universidad'], $postulante['carrera']);

            // Fixture dates are synthetic, explicit demo data, never a historical backfill.
            // Re-running this seeder must not assign a made-up birthday to an existing record.
            $existing = Postulante::withTrashed()->where('ci_post', $postulante['ci_post'])->first();
            if ($existing) {
                unset($postulante['fecha_nacimiento_post']);
            }

            Postulante::withTrashed()->updateOrCreate(
                ['ci_post' => $postulante['ci_post']],
                [
                    ...$postulante,
                    'id_col' => $colegios[$colegio],
                    'id_car' => $carreras[$carreraKey]->id_car,
                    'observaciones_post' => 'Registro institucional de seguimiento académico.',
                ]
            );
        }
    }
}
