import options from '../../input-options.json';

export { options as inputOptions };

// UX hints only. Laravel Form Requests remain authoritative.
export const inputConstraints = {
    "nombre_cargo": {"required":true,"minLength":2,"maxLength":160,"format":"denomination"},
    "nombres": {"required":true,"minLength":2,"maxLength":120,"format":"person"},
    "apellidos": {"required":true,"minLength":2,"maxLength":120,"format":"person"},
    "ci": {"minLength":4,"maxLength":30,"format":"document"},
    "celular": {"maxLength":32,"format":"phone","type":"tel","inputMode":"tel"},
    "correo_contacto": {"maxLength":254,"format":"email","type":"email"},
    "id_sim": {"inputMode":"numeric","step":1},
    "tipo_eval_apl": {"maxLength":120},
    "id_preg": {"inputMode":"numeric","step":1},
    "id_alt": {"inputMode":"numeric","step":1},
    "respuesta_texto": {"maxLength":5000},
    "tiempo_segundos": {"inputMode":"numeric","step":1,"min":0,"max":2147483647},
    "intentos": {"inputMode":"numeric","step":1,"min":1,"max":32767},
    "tiempo_total_segundos": {"inputMode":"numeric","step":1,"min":0,"max":2147483647},
    "name": {"required":true,"minLength":2,"maxLength":255,"format":"person"},
    "email": {"required":true,"maxLength":254,"format":"email","type":"email"},
    "nombres_post": {"required":true,"minLength":2,"maxLength":120,"format":"person"},
    "apellidos_post": {"required":true,"minLength":2,"maxLength":120,"format":"person"},
    "ci_post": {"minLength":4,"maxLength":30,"format":"document"},
    "email_post": {"maxLength":254,"format":"email","type":"email"},
    "celular_post": {"maxLength":32,"format":"phone","type":"tel","inputMode":"tel"},
    "fecha_nacimiento_post": {"maxLength":10,"minLength":10,"pattern":"[0-9]{2}/[0-9]{2}/[0-9]{4}"},
    "id_col": {"inputMode":"numeric","step":1},
    "id_uni": {"inputMode":"numeric","step":1},
    "id_car": {"inputMode":"numeric","step":1},
    "turno_post": {},
    "gestion_post": {"required":true,"inputMode":"numeric","step":1,"min":2000},
    "estado_post": {"required":true},
    "observaciones_post": {"maxLength":2000},
    "user_id": {"inputMode":"numeric","step":1},
    "nombres_tutor": {"required":true,"minLength":2,"maxLength":120,"format":"person"},
    "apellidos_tutor": {"required":true,"minLength":2,"maxLength":120,"format":"person"},
    "ci_tutor": {"minLength":4,"maxLength":30,"format":"document"},
    "celular_tutor": {"maxLength":32,"format":"phone","type":"tel","inputMode":"tel"},
    "correo_tutor": {"maxLength":180,"format":"email","type":"email"},
    "especialidad_tutor": {"maxLength":160},
    "formacion_tutor": {"maxLength":220},
    "experiencia_tutor": {"maxLength":3000},
    "estado_tutor": {"required":true},
    "observacion_tutor": {"maxLength":2000},
    "id_prog": {"inputMode":"numeric","step":1},
    "id_grupo": {"inputMode":"numeric","step":1},
    "id_plantilla": {"inputMode":"numeric","step":1},
    "titulo_sim": {"required":true,"minLength":2,"maxLength":180},
    "fecha_sim": {},
    "hora_inicio_sim": {},
    "hora_fin_sim": {},
    "modalidad_sim": {"maxLength":100},
    "estado_sim": {"required":true},
    "observacion_sim": {"maxLength":2000},
    "nombre_prog": {"required":true,"minLength":2,"maxLength":180},
    "codigo_prog": {"minLength":2,"maxLength":60,"format":"code"},
    "universidad_objetivo_prog": {"maxLength":180},
    "carrera_area_prog": {"maxLength":180},
    "modalidad_prog": {"maxLength":100},
    "fecha_inicio_prog": {},
    "fecha_fin_prog": {},
    "descripcion_prog": {"maxLength":3000},
    "estado_prog": {"required":true},
    "id_insc": {"inputMode":"numeric","step":1},
    "codigo_mat": {"minLength":2,"maxLength":60,"format":"code"},
    "fecha_matricula_mat": {},
    "monto_matricula_mat": {"required":true,"inputMode":"decimal","step":0.01,"min":0,"max":99999999.99},
    "estado_matricula_mat": {"required":true},
    "tipo_beneficio_mat": {"maxLength":120},
    "observacion_mat": {"maxLength":2000},
    "id_post": {"inputMode":"numeric","step":1},
    "fecha_inscripcion": {},
    "estado_inscripcion": {"required":true},
    "observacion_inscripcion": {"maxLength":2000},
    "estado_hab": {"required":true},
    "motivo_hab": {"maxLength":220},
    "fecha_inicio_hab": {},
    "fecha_fin_hab": {},
    "habilitado_evaluaciones_hab": {},
    "habilitado_simulacros_hab": {},
    "habilitado_reportes_hab": {},
    "observacion_hab": {"maxLength":2000},
    "nombre_grupo": {"required":true,"minLength":2,"maxLength":160},
    "codigo_grupo": {"minLength":2,"maxLength":60,"format":"code"},
    "turno_grupo": {"maxLength":80},
    "aula_grupo": {"maxLength":80},
    "capacidad_grupo": {"required":true,"inputMode":"numeric","step":1,"min":1,"max":500},
    "nivel_grupo": {"maxLength":100},
    "tutor_responsable_grupo": {"minLength":2,"maxLength":180,"format":"person"},
    "estado_grupo": {"required":true},
    "id_mat": {"inputMode":"numeric","step":1},
    "nro_cuota": {"inputMode":"numeric","step":1,"min":1,"max":120},
    "concepto_cuota": {"maxLength":180},
    "monto_cuota": {"required":true,"inputMode":"decimal","step":0.01,"min":0,"max":99999999.99},
    "fecha_vencimiento_cuota": {},
    "fecha_pago_cuota": {},
    "metodo_pago_cuota": {"maxLength":120},
    "estado_cuota": {"required":true},
    "observacion_cuota": {"maxLength":2000},
    "id_tutor": {"inputMode":"numeric","step":1},
    "fecha_asist": {"required":true},
    "sesion_asist": {"required":true,"minLength":2,"maxLength":120},
    "estado_asist": {"required":true},
    "observacion_asist": {"maxLength":2000},
    "materia_referencia_asig": {"maxLength":160},
    "rol_asig": {"maxLength":120},
    "fecha_inicio_asig": {},
    "fecha_fin_asig": {},
    "estado_asig": {"required":true},
    "observacion_asig": {"maxLength":2000},
    "id_area": {"inputMode":"numeric","step":1},
    "nombre_tem": {"required":true,"maxLength":120,"minLength":2},
    "descripcion_tem": {"maxLength":2000},
    "nivel_tem": {},
    "estado_tem": {"required":true},
    "nombre_area": {"required":true,"maxLength":120,"minLength":2},
    "descripcion_area": {"maxLength":2000},
    "estado_area": {"required":true},
    "id_tem": {"inputMode":"numeric","step":1},
    "subtema_preg": {"maxLength":255},
    "enunciado_preg": {"required":true,"maxLength":5000},
    "tipo_preg": {"required":true},
    "dificultad_preg": {},
    "exigencia_preg": {},
    "habilidad_preg": {},
    "tiempo_estimado_seg_preg": {"inputMode":"numeric","step":1,"min":15,"max":7200},
    "relacion_ingenieria_preg": {"maxLength":2000},
    "puntaje_preg": {"required":true,"inputMode":"decimal","step":0.01,"min":0.01,"max":100},
    "explicacion_preg": {"maxLength":5000},
    "estado_preg": {"required":true},
    "texto_alt": {"required":true,"maxLength":2000},
    "letra_alt": {},
    "es_correcta_alt": {},
    "orden_alt": {"inputMode":"numeric","step":1,"min":1,"max":5},
    "estado_alt": {},
    "nombre_plan": {"required":true,"minLength":2,"maxLength":180},
    "descripcion_plan": {"maxLength":3000},
    "objetivo_plan": {"maxLength":3000},
    "duracion_minutos_plan": {"inputMode":"numeric","step":1,"min":1,"max":480},
    "dificultad_plan": {},
    "estado_plan": {"required":true},
    "orden_pp": {"required":true,"inputMode":"numeric","step":1,"min":1,"max":1000},
    "puntaje_pp": {"required":true,"inputMode":"decimal","step":0.01,"min":0.01,"max":100},
    "current_password": {},
    "password": {},
    "password_confirmation": {},
    "token": {"required":true,"maxLength":255},
    "remember": {},
    "role": {"required":true},
};

const patterns = {
    denomination: String.raw`[\s\S]*\p{L}[\s\S]*`,
    person: String.raw`\s*[\p{L}\p{M}]+(?:[ '\u2019\-]+[\p{L}\p{M}]+)*\s*`,
    document: String.raw`\s*(?=.*[0-9])[A-Za-z0-9]+(?:[ .\/\-][A-Za-z0-9]+)*\s*`,
    phone: String.raw`\+?[0-9\s\(\)\-]+`,
    code: String.raw`\s*[A-Za-z0-9]+(?:[_\-][A-Za-z0-9]+)*\s*`,
};

export function validationProps(field, overrides = {}) {
    const key = field.split('.').at(-1);
    const { format, ...props } = inputConstraints[key] || {};
    if (patterns[format]) props.pattern = patterns[format];
    if (key === 'gestion_post') props.max = new Date().getFullYear() + 1;
    return { name: field, ...props, ...overrides };
}
